package application;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

/**
 * Main class extends javafx application class and connects the model, view and controller
 */
public class Main extends Application {

    /**
     * starts JavaFX application with stage generated by JavaFX runtime
     */
    @Override
    public void start(Stage primaryStage) throws Exception{
        Parent root = FXMLLoader.load(getClass().getResource("../view/mainmenu.fxml"));
        primaryStage.setTitle("Java Cafe Rutgers");
        primaryStage.setScene(new Scene(root, 1024, 768));
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
